name: barbearia_saas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  flutter_riverpod: ^2.4.0
  flutter_hooks: ^0.21.2
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.2.2
  fl_chart: ^1.0.0
  intl: ^0.20.2
  flutter_multi_formatter: ^2.5.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  cloudinary_sdk: ^5.0.0+1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
